# GitHub Actions workflow to build and deploy a VitePress site to GitHub Pages

name: Deploy VitePress to GitHub Pages

on:
  push:
    branches: [main] # Trigger the workflow on pushes to the main branch
  workflow_dispatch: # Allow manual runs of the workflow from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

# Define concurrency to prevent overlapping runs
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job: Builds the VitePress app
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # You can specify your preferred Node.js version
          cache: npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci # Or `pnpm install` / `yarn install` if you're using other package managers

      # Step 4: Build the VitePress app
      - name: Build VitePress app
        run: npm run docs:build # Or `pnpm docs:build` / `yarn docs:build`

      # Step 5: Upload the built site as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  # Deploy job: Deploys the built site to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Deploy to GitHub Pages with deploy-pages action
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2